version: '3'

services:
  mongo-server:
    container_name: mongo-server
    image: mongo
    networks: 
      - business-net
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: businessDB
  
  api:
    build: .
    environment:
      MONGO_HOST: '192.168.99.100'
      MONGO_PORT: 27017
      MONGO_USER: 'businessUser'
      MONGO_PASSWORD: password
      MONGO_DB_NAME: businessDB
      PORT: 8000
    ports:
      - "8000:8000"
    links:
      - mongo